import Link from "next/link"
import { ArrowUpRightIcon, GithubIcon } from "lucide-react"
import { MarkdownContent } from "@/app/components/MarkdownContent"
import {
  publicActionButtonBaseClassName,
  publicActionSizeClassName,
  publicPrimaryActionClassName,
  publicSecondaryActionClassName,
} from "@/app/components/public-capsules"
import { Button } from "@/components/ui/button"
import { getChangelogEntries } from "@/lib/changelog"

function formatPublishedAt(value: string | null) {
  if (!value) return "Pending date"

  return new Intl.DateTimeFormat("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  }).format(new Date(value))
}

export default async function ChangelogsPage() {
  const { entries, hasError } = await getChangelogEntries()
  const [latest, ...rest] = entries

  return (
    <>
      <section className="grid gap-6 border-b border-border/70 pb-10 lg:grid-cols-[1.2fr_0.8fr]">
        <div className="space-y-4">
          <p className="text-xs uppercase tracking-[0.28em] text-muted-foreground">
            Release Notes
          </p>
          <h1 className="max-w-3xl text-4xl font-semibold tracking-tight text-balance sm:text-6xl">
            Changelogs rendered directly from the project’s release markdown.
          </h1>
        </div>
        <div className="space-y-4 rounded-[2rem] border border-border/70 bg-muted/35 p-6">
          <p className="text-sm leading-7 text-foreground/85">
            Source: the root <code className="rounded bg-background px-1.5 py-0.5 font-mono text-[0.9em] text-foreground">CHANGELOG.md</code> file generated by the release workflow.
          </p>
          <div className="flex flex-wrap gap-3">
            <Button
              asChild
              className={`${publicActionButtonBaseClassName} ${publicPrimaryActionClassName} ${publicActionSizeClassName}`}
            >
              <Link href="/app">
                Open App
                <ArrowUpRightIcon className="size-3.5" aria-hidden="true" />
              </Link>
            </Button>
            <Button
              asChild
              variant="outline"
              className={`${publicActionButtonBaseClassName} ${publicSecondaryActionClassName} ${publicActionSizeClassName}`}
            >
              <a
                href="https://github.com/design-sparx/parse-pal/blob/main/CHANGELOG.md"
                target="_blank"
                rel="noreferrer"
              >
                <GithubIcon className="size-4" aria-hidden="true" />
                View changelog source
                <ArrowUpRightIcon className="size-3.5" aria-hidden="true" />
              </a>
            </Button>
          </div>
        </div>
      </section>

      {hasError && entries.length === 0 ? (
        <section className="rounded-[2rem] border border-border/70 bg-muted/35 p-8">
          <p className="text-xs uppercase tracking-[0.28em] text-muted-foreground">
            Unavailable
          </p>
          <h2 className="mt-3 text-2xl font-semibold tracking-tight">
            The changelog could not be loaded in-app.
          </h2>
          <p className="mt-4 max-w-2xl text-sm leading-8 text-foreground/85">
            The release notes still live in the repository. Open the source changelog
            directly on GitHub while the in-app reader is unavailable.
          </p>
          <Button
            asChild
            variant="outline"
            className={`mt-6 ${publicActionButtonBaseClassName} ${publicSecondaryActionClassName} ${publicActionSizeClassName}`}
          >
            <a
              href="https://github.com/design-sparx/parse-pal/blob/main/CHANGELOG.md"
              target="_blank"
              rel="noreferrer"
            >
              Open on GitHub
            </a>
          </Button>
        </section>
      ) : null}

      {!hasError && !latest ? (
        <section className="rounded-[2rem] border border-border/70 bg-muted/35 p-8">
          <p className="text-xs uppercase tracking-[0.28em] text-muted-foreground">
            No Releases Yet
          </p>
          <h2 className="mt-3 text-2xl font-semibold tracking-tight">
            The release pipeline is in place. The first published notes will show up
            here after the next release.
          </h2>
          <p className="mt-4 max-w-2xl text-sm leading-8 text-foreground/85">
            Until then, the repository is the best place to follow the project and
            inspect the active implementation work.
          </p>
          <Button
            asChild
            variant="outline"
            className={`mt-6 ${publicActionButtonBaseClassName} ${publicSecondaryActionClassName} ${publicActionSizeClassName}`}
          >
            <Link href="/about">Read about the project</Link>
          </Button>
        </section>
      ) : null}

      {latest ? (
        <section className="grid gap-8 lg:grid-cols-[0.7fr_1.3fr]">
          <div className="space-y-4">
            <p className="text-xs uppercase tracking-[0.28em] text-muted-foreground">
              Latest Release
            </p>
            <div className="space-y-2">
              <h2 className="text-3xl font-semibold tracking-tight">{latest.title}</h2>
              <p className="text-sm leading-7 text-muted-foreground">
                {formatPublishedAt(latest.publishedAt)}
              </p>
            </div>
          </div>
          <article className="rounded-[2rem] border border-border/70 bg-muted/35 p-6 sm:p-8">
            {latest.body ? (
              <MarkdownContent content={latest.body} />
            ) : (
              <p className="text-sm leading-7 text-foreground/85">
                This release has a heading but no detailed notes yet.
              </p>
            )}
          </article>
        </section>
      ) : null}

      {rest.length > 0 ? (
        <section className="border-t border-border/70 pt-10">
          <div className="mb-8 flex items-end justify-between gap-6">
            <div className="space-y-2">
              <p className="text-xs uppercase tracking-[0.28em] text-muted-foreground">
                Archive
              </p>
              <h2 className="text-2xl font-semibold tracking-tight">
                Earlier release notes
              </h2>
            </div>
          </div>
          <div className="space-y-6">
            {rest.map((entry) => (
              <article
                key={entry.slug}
                className="grid gap-6 rounded-[1.75rem] border border-border/70 bg-background p-6 lg:grid-cols-[16rem_1fr]"
              >
                <div className="space-y-2">
                  <h3 className="text-xl font-semibold tracking-tight">{entry.title}</h3>
                  <p className="text-sm leading-7 text-muted-foreground">
                    {formatPublishedAt(entry.publishedAt)}
                  </p>
                </div>
                {entry.body ? (
                  <MarkdownContent content={entry.body} />
                ) : (
                  <p className="text-sm leading-7 text-foreground/85">
                    This release has no detailed notes yet.
                  </p>
                )}
              </article>
            ))}
          </div>
        </section>
      ) : null}
    </>
  )
}
